#!/usr/bin/env python3
"""Tests for fingerprint-importmap.py, the post-publish loader fix.

The script decides whether it has already run by looking at index.html. That
decision is the whole risk in it: when it wrongly decides yes, it skips, and a
published site that cannot boot ships behind a green build and a zero exit
code. There is no louder signal than that, so the decision is tested here
rather than trusted.

It once tested `"importmap" in html`, which cannot tell the thing from a
mention of the thing. A comment in index.html naming the script by its own
file name contains that word, and switched it off. Both directions are
asserted below: a mention must not stop it, and a real element must.

Run with:

    python3 -m unittest discover -s tests -v
"""
import importlib.util
import pathlib
import unittest

REPO = pathlib.Path(__file__).resolve().parent.parent
SCRIPT = REPO / "fingerprint-importmap.py"
APP_INDEX = REPO / "src" / "OasBrowser" / "wwwroot" / "index.html"

# The script's file name is not an identifier, so it cannot be imported by
# name. Load it by path instead, and test the real thing rather than a copy of
# its regex.
_spec = importlib.util.spec_from_file_location("fingerprint_importmap", SCRIPT)
fingerprint = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(fingerprint)

HASHED_RUNTIME = "dotnet.ducu1w6ht9.js"
LOADER = '    <script src="_framework/blazor.webassembly.js"></script>'

# The real element, as this script and the SDK both write it.
REAL_IMPORT_MAP = (
    '    <script type="importmap">\n'
    '    {"imports": {"/oas-browser/_framework/dotnet.js":'
    ' "/oas-browser/_framework/already-there.js"}}\n'
    '    </script>'
)


def page(body_extra: str = "", head_extra: str = "") -> str:
    """A minimal index.html of the shape this script is pointed at."""
    return (
        "<!DOCTYPE html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        '    <meta charset="utf-8" />\n'
        f"{head_extra}"
        '    <base href="/oas-browser/" />\n'
        "</head>\n"
        "<body>\n"
        '    <div id="app"></div>\n'
        f"{body_extra}"
        f"{LOADER}\n"
        "</body>\n"
        "</html>\n"
    )


class ScriptRun(unittest.TestCase):
    """Runs the real main() against a throwaway published wwwroot."""

    def run_against(self, html: str, runtime: str = HASHED_RUNTIME):
        import tempfile

        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        wwwroot = pathlib.Path(tmp.name)
        (wwwroot / "_framework").mkdir()
        if runtime:
            (wwwroot / "_framework" / runtime).write_text("// runtime\n")
        index = wwwroot / "index.html"
        index.write_text(html)
        code = fingerprint.main(wwwroot)
        return code, index.read_text()

    def assertInjected(self, before: str):
        code, after = self.run_against(before)
        self.assertEqual(code, 0)
        self.assertNotEqual(after, before, "the script skipped when it had to inject")
        self.assertIn(f'"/oas-browser/_framework/{HASHED_RUNTIME}"', after)
        return after

    def assertSkipped(self, before: str):
        code, after = self.run_against(before)
        self.assertEqual(code, 0)
        self.assertEqual(after, before, "the script injected when it had to skip")


class MentionsMustNotStopIt(ScriptRun):
    """Direction one: the word is not the element."""

    def test_injects_when_importmap_appears_only_in_a_comment(self):
        # The exact shape that nearly shipped: a comment naming the script by
        # its own file name, which contains the word.
        html = page(head_extra=(
            "    <!-- Do not rename this: the post-publish step\n"
            "         fingerprint-importmap.py is wired to this file. -->\n"
        ))
        self.assertIn("importmap", html)
        self.assertInjected(html)

    def test_injects_when_a_whole_import_map_is_commented_out(self):
        # Commented-out markup is still only a mention. Erring towards
        # injecting is the safe direction: a duplicate map is visible at once,
        # a missing one is a site that does not start.
        self.assertInjected(page(body_extra=f"    <!--\n{REAL_IMPORT_MAP}\n    -->\n"))

    def test_injects_when_importmap_is_only_a_prose_word_in_the_body(self):
        self.assertInjected(page(body_extra="    <p>Generated by an importmap step.</p>\n"))

    def test_injects_when_the_word_is_another_element_s_attribute(self):
        # data-type is not the type attribute, and importmap-shim is not this
        # element. Neither is an import map.
        self.assertInjected(page(body_extra=(
            '    <script data-type="importmap" src="js/app.js"></script>\n'
            '    <script type="importmap-shim">{"imports":{}}</script>\n'
        )))

    def test_the_shipped_index_html_actually_gets_a_map(self):
        # The regression guard proper, and the reason the others are not
        # enough: it runs the real decision against the real file. index.html
        # is hand-authored and carries prose naming this script, so a mention
        # is not a hypothetical there, it is committed. Publish copies it
        # unchanged, so what happens to it here is what happens on deploy.
        source = APP_INDEX.read_text()
        self.assertIn("importmap", source, "the guard is only meaningful while "
                                           "index.html mentions the word at all")
        self.assertInjected(source)


class ElementsMustStopIt(ScriptRun):
    """Direction two: the element is not to be duplicated."""

    def test_skips_when_an_import_map_element_is_already_present(self):
        self.assertSkipped(page(body_extra=REAL_IMPORT_MAP + "\n"))

    def test_skips_when_the_type_is_single_quoted(self):
        self.assertSkipped(page(body_extra="    <script type='importmap'>{}</script>\n"))

    def test_skips_when_the_type_is_unquoted(self):
        self.assertSkipped(page(body_extra="    <script type=importmap>{}</script>\n"))

    def test_skips_when_the_type_carries_odd_spacing_and_case(self):
        self.assertSkipped(page(body_extra='    <SCRIPT TYPE = "ImportMap">{}</SCRIPT>\n'))

    def test_skips_when_other_attributes_precede_the_type(self):
        self.assertSkipped(page(
            body_extra='    <script id="map" type="importmap">{}</script>\n'))


class WhatItWritesWhenItRuns(ScriptRun):
    """The injected map has to resolve, or running was no better than skipping."""

    def test_the_map_is_keyed_on_the_base_href(self):
        # Import map keys are resolved specifiers. A map keyed on anything but
        # the base href does not resolve, and the page dies on first import.
        after = self.assertInjected(page())
        self.assertIn('"/oas-browser/_framework/dotnet.js"', after)

    def test_the_map_is_written_before_the_loader_that_imports(self):
        after = self.assertInjected(page())
        self.assertLess(
            after.index('type="importmap"'),
            after.index("blazor.webassembly"),
            "an import map after the loader is too late to redirect it",
        )

    def test_a_second_run_over_its_own_output_skips(self):
        # Idempotence is the property the check exists for, so assert it end to
        # end rather than inferring it from the two directions above.
        once = self.assertInjected(page())
        self.assertSkipped(once)

    def test_leaves_the_page_alone_when_nothing_is_fingerprinted(self):
        html = page()
        code, after = self.run_against(html, runtime="")
        self.assertEqual(code, 0)
        self.assertEqual(after, html)


if __name__ == "__main__":
    unittest.main()
